### ISSUE TITLE
[solved] serverProcessStop() execution timed out

### ISSUE THREAD

**Issue by Nik99** [par0noid/ts3admin.class#1]
So im actually building a teamspeak 3 web panel with ts3admin class because i personally find it very easy to use, fast and very very easy to implement.

But, when i try to stop a server process, the server stops himself, but ts3admin keeps running and the server returns me max execution time limit exceeded.

this is my code:

`
        $teamspeak = new ts3admin($data->ip, $data->sq_port);
        
        if($teamspeak->getElement('success', $teamspeak->connect())) {
          
          if($teamspeak->login($data->sq_username, $data->sq_password)) {
            
            if($teamspeak->serverProcessStop()) {
              $response = true;
            } else {
              $response = false;
            }
          } else {
            $response = false;
          }
        }`

**Comment by par0noid** [comment]
Hey,

you're doing some things really wrong. **Every ts3admin.class request returns an Array** with following elements: **success, data and error**.

if($teamspeak->login($data->sq_username, $data->sq_password)) {

or

if($teamspeak->serverProcessStop()) {

won't look at the 'success' element.

You're code should look like this:

```
if($teamspeak->getElement('success', $teamspeak->connect())) {
	if($teamspeak->getElement('success', $teamspeak->login($data->sq_username, $data->sq_password))) {
		if($teamspeak->getElement('success', $teamspeak->serverProcessStop())) {
			$response = true;
		} else {
			$response = false;
		}
	} else {
		$response = false;
	}
}
```

**Comment by Nik99** [comment]
Now i understand why i was always returning true from the servers.

Thanks, paran0id. You are the best
