### ISSUE TITLE
No composer.json available

### ISSUE THREAD

**Issue by muuvmuuv** [par0noid/ts3admin.class#11]
Could you please create a composer.json file. I want to work with your class in some project where I need to use composer (for updates etc.).

Regards

**Comment by thomas-rolling** [comment]
Great idea, we need it to use in SF3 project.

**Comment by Nik99** [comment]
Actually @par0noid doesnt seems to be very active here.

**Comment by muuvmuuv** [comment]
@thomas-rolling @Nik99. I have forked it: https://github.com/muuvmuuv/ts3admin.class
Not sure if this this is the right composer.json (first time with composer), but feel free to great a issue.

**Comment by Nik99** [comment]
@muuvmuuv Shouldn't be better with psr-4 ?

**Comment by muuvmuuv** [comment]
I can change it to. Make an issue @Nik99

**Comment by thomas-rolling** [comment]
Try a pull request ?

Now it's very useful to have a composer.json.

**Comment by par0noid** [comment]
Thanks to @muuvmuuv 
Take a look at https://github.com/par0noid/ts3admin.class/commit/d83a2f77724b1c4f9c3cc23d7bd72319e2c0e488

**Comment by par0noid** [comment]
I've one question left: File ok? Improvements? I've no clue how these composer-files work, never used

**Comment by Nik99** [comment]
@par0noid, for what i know, it should be better to make it with psr-4 standard (used by most, laravel for example)

**Comment by DavidBonnier** [comment]
@par0noid 
You can add ;
## Specific version
> "version": "1.0.1.3"
Is the last version load automatily by composer, you can add in line to.

## Add where is source

> "source": {
>     "type": "git",
>     "url": "https://github.com/par0noid/ts3admin.class.git",
>     "reference": "5583baad4b4e954551353cf5e653f4214028b5c9"
> },
> "dist": {
>     "type": "zip",
>     "url": "https://api.github.com/repos/par0noid/ts3admin.class/zipball/5583baad4b4e954551353cf5e653f4214028b5c9",
>     "reference": "5583baad4b4e954551353cf5e653f4214028b5c9",
>     "shasum": ""
> },

5583baad4b4e954551353cf5e653f4214028b5c9 is hash for commit version 1.0.1.3, I found in https://github.com/par0noid/ts3admin.class/commit/5583baad4b4e954551353cf5e653f4214028b5c9

## Add a new version
You can add a new version with composer.json (1.0.1.4) else composer not found your composer.json

Thank you for my project with @thomas-rolling in SF3

PS : In author you can add for exemple @toxiicdev or other but you are free

**Comment by par0noid** [comment]
thanks @DavidBonnier

**Comment by DrDelay** [comment]
You could also just omit the `version` & `repositories` directives and publish your project on [Packagist](https://packagist.org/). This way people who want to use your library can just type `composer require par0noid/ts3admin`, as Packagist is the main repository Composer will look into.

Packagist also automatically takes care of versioning, using the Git tags of your repository. See https://getcomposer.org/doc/04-schema.md#version :
> The version of the package. In most cases this is not required and should be omitted (see below).
> Optional if the package repository can infer the version from somewhere, such as the VCS tag name in the VCS repository. In that case it is also recommended to omit it.
