### ISSUE TITLE
Any way to get icons ?

### ISSUE THREAD

**Issue by Nik99** [par0noid/ts3admin.class#13]
Actually i'm a bit lost.
Is there any way to get teamspeak icons with their own id and image ? (base64 or direct file, i don't care)

**Comment by par0noid** [comment]
Think that they are stored in channel ID 0 or something like that. There also -icon parameters on several functions

**Comment by Nik99** [comment]
Referring to your direct documentation, in channelInfo() function there is:
[channel_icon_id] => 0
If i get the id, where can i actually use it ?

**Comment by par0noid** [comment]
`Array
(
    [success] => 1
    [errors] => Array
        (
        )

    [data] => Array
        (
            [pid] => 0
            [channel_name] => easads
            [channel_topic] => 
            [channel_description] => 
            [channel_password] => 
            [channel_codec] => 4
            [channel_codec_quality] => 6
            [channel_maxclients] => -1
            [channel_maxfamilyclients] => -1
            [channel_order] => 1
            [channel_flag_permanent] => 1
            [channel_flag_semi_permanent] => 0
            [channel_flag_default] => 0
            [channel_flag_password] => 0
            [channel_codec_latency_factor] => 1
            [channel_codec_is_unencrypted] => 1
            [channel_security_salt] => 
            [channel_delete_delay] => 0
            [channel_flag_maxclients_unlimited] => 1
            [channel_flag_maxfamilyclients_unlimited] => 0
            [channel_flag_maxfamilyclients_inherited] => 1
            [channel_filepath] => files\\virtualserver_1\\channel_2
            [channel_needed_talk_power] => 0
            [channel_forced_silence] => 0
            [channel_name_phonetic] => 
            [channel_icon_id] => -25267377
            [channel_flag_private] => 0
            [seconds_empty] => 1074
        )

)
Array
(
    [success] => 1
    [errors] => Array
        (
        )

    [data] => Array
        (
            [0] => Array
                (
                    [cid] => 0
                    [path] => /icons/
                    [name] => icon_4269699919
                    [size] => 733
                    [datetime] => 1478089525
                    [type] => 1
                )

        )

)`

First is channelInfo, second is ftGetFileList(0,'','/icons/')

The IconID is a negative value because the real iconID reaches the max of INT32, add 2^32 to the iconID and you'll have the real iconID

**Comment by Nik99** [comment]
Nice trick!

You should create a function like getIcon($iconid, $path) or getIcon($iconid) that does this, or at least put this in the documentation to make it published for everyone ;)

@par0noid

**Comment by par0noid** [comment]
Yea, also tought about it. Just TYI: Teamspeak stores avatars at the root of channel 0, and icons at /icons/

**Comment by par0noid** [comment]
I would like to know if teamspeak always give ID's > 2^32 to icons

**Comment by Nik99** [comment]
We can ask to teamspeak devs. Let me create a support thread
Btw, waiting for a v1.0.1.5 with this function :)

**Comment by Nik99** [comment]
http://forum.teamspeak.com/threads/127792-Does-Teamspeak-always-give-ID-s-gt-2-32-to-icons?p=437743#post437743 @par0noid here we go

**Comment by par0noid** [comment]
Added channelGetIconByID on https://github.com/par0noid/ts3admin.class/commit/6343dd370a0e650a21d66aeba52db9511e560a4a

I'll add a function for getIcon by ChannelID when we know the INT32 thing

**Comment by Nik99** [comment]
So this function actually wants the negative channel id ?

**Comment by par0noid** [comment]
No, the real one, i would recommend to give it as a string

**Comment by par0noid** [comment]
Best thing is: when you want to download the icon with ft-functions, teamspeak says that the file is not available at /icons/icon_123456, they're storing them internal to /icon_123456

**Comment by Nik99** [comment]
Yes sorry i was meaning iconID.
Btw, teamspeak devs answered.

**Comment by par0noid** [comment]
https://github.com/par0noid/ts3admin.class/commit/ccab1b51874cb4ce621a6f5c78f9694da7827a32

**Comment by Nik99** [comment]
So this function will automatically get the icon by giving the channel id ?

**Comment by par0noid** [comment]
yes

**Comment by Nik99** [comment]
Well done @par0noid.
Those are really sick functionalities. :)

**Comment by Nik99** [comment]
Ps: Don't forget the update the doc

**Comment by par0noid** [comment]
Updated. :)

**Comment by Nik99** [comment]
Well i think we can close the issue.
