### ISSUE TITLE
Misspelled channel property 'CHANNEL_CODEC'

### ISSUE THREAD

**Issue by Micky5991** [par0noid/ts3admin.class#15]
I just noticed a small mistake in the documentation. In the list of possible properties in `channelCreate($data)`, there is a property called `CHANNEL CODEC`, but it lacks an underscore (`CHANNEL_CODEC`).

And maybe it should be documented in lowercases or transformed to it by default, because the query doesn't accept them in other forms than lowercase.

**Comment by Sebi94nbg** [comment]
I've added a pull request for this issue: #16 :)

If it needs to be in lowercase or not, should @par0noid answer, because he has developed the class and knows, if it will be formatted by the class or not. Let's wait for his feedback.

**Comment by par0noid** [comment]
Thank you guys, I did a commit https://github.com/par0noid/ts3admin.class/commit/14f19b0a5ba319933f990e75a6831c930eb06194

**Comment by Nik99** [comment]
@par0noid shouldn't lowercase be applied to all edit functions ?

**Comment by Nik99** [comment]
Oops, mistake 
Didn't see the complete commit, nvm

**Comment by par0noid** [comment]
@Nik99 Could happen to anyone 😊
