### ISSUE TITLE
getting users in channel

### ISSUE THREAD

**Issue by psukys** [par0noid/ts3admin.class#18]
Hey, I've tried finding, yet failed, how to list the clients in a  channel. The only channel related information for a client found: "Default channel". Is there a way of finding out what users are currently in a channel?
Thanks!

**Comment by Nik99** [comment]
A way to solve this would be to get clientList() and  check which users haves your channel id @psukys
Maybe @par0noid got better solutions

**Comment by AdrianSchega** [comment]
`function channelClientList($your_channel_id){
    global $tsAdmin;
    $arr = [];
    foreach($tsAdmin->clientList()['data'] as $client){
        if($client['cid'] == $your_channel_id){
            $arr[] = $client;
        }
    }
    return $arr;
}`

**Comment by par0noid** [comment]
The only way to find out which users are in a specific channel is to do a clientlist and check for their channelIDs
