### ISSUE TITLE
Error in connect() on line 4388: host isn't a ts3 instance!

### ISSUE THREAD

**Issue by GryTrean** [par0noid/ts3admin.class#21]
Hey!
When I first run my code, there is no problem with connectig.
After I have terminated it through my console, I get this error while trying to connect: Error in connect() on line 4388: host isn't a ts3 instance!

Then I have to wait something about 15 minutes before I can use it again.
Can someone explain why it is like that?
My code:
`<?php

require_once("includes/ts3admin.class.php");
require_once("config.php");

$tsAdmin = new ts3admin($config['connect']['ip'], $config['connect']['qPort']);

function PokeAllAdmins($message)
{
	global $tsAdmin;
	foreach($tsAdmin->clientList() as $clients)
	{
		if($clients['cid'] == 5)
		{
			echo "Gracz znajduje sie na CP!";
			foreach($ts3->clientList("-groups") as $client)
			{
				if($tsAdmin->getElement("9", $client["client_servergroups"]))
				{
					$tsAdmin->clientPoke($client, $message);
				}
			}
		} 
	}
}

if($tsAdmin->getElement('success', $tsAdmin->connect()))
{
	$tsAdmin->login($config['connect']['qName'], $config['connect']['qPass']);
	$tsAdmin->selectServer($config['connect']['port']);
	$tsAdmin->setName($config['botSettings']['nick']);
	echo "Polaczono z serwerem!\n";

	$clients = $tsAdmin->clientList();
	echo count($clients['data'])." osob online na serwerze\n\n";

	if(count($tsAdmin->getDebugLog()) > 0)
	{
		foreach($tsAdmin->getDebugLog() as $logEntry)
		{
			print_r($logEntry);
		}
	}

	while(true)
	{
		$clients = $tsAdmin->clientList();
		$data['virtualserver_name'] = "TestowyTS [Online: ".count($clients['data'])."]";
		$tsAdmin->serverEdit($data);
		PokeAllAdmins("Użytkownik znajduje się na Centrum Pomocy!");
		sleep(5);
	}
}

if(count($tsAdmin->getDebugLog()) > 0) {
	foreach($tsAdmin->getDebugLog() as $logEntry) {
		echo "[C] ".$logEntry."\n";
	}
};

?>

`

Thanks
GryTrean

**Comment by Viper61** [comment]
Hi,

This is a TeamSpeak security thing. It limit the number of query request received by IP.
To avoid this, you should add your host IP on the query whitelist file.

**Comment by par0noid** [comment]
@Viper61 right! 👍
