### ISSUE TITLE
serialize/ unserialize object

### ISSUE THREAD

**Issue by lgund** [par0noid/ts3admin.class#22]
Hey,
ich versuche verzweifelt, ein erstelltes Object der ts3admin class zu serializieren bzw. zu deserializieren.

Mein Ansatz ist der:
`	require_once("../ts3admin.class.php");
	
	$tsAdmin = new ts3admin('85.214.197.205', 10011);
	
	if($tsAdmin->getElement('success', $tsAdmin->connect()))
	{
		// Im Teamspeak Einloggen
		$tsAdmin->login('serveradmin', '{ZENSIERT}');
		
		// Server Select
		$tsAdmin->selectServer(33, 'serverId', true);
		
		// Server Info Daten abfragen
		$server = $tsAdmin->serverInfo();
	};
	
	//print_r($tsAdmin);
	echo serialize($tsAdmin);
	echo "<br/><br/>".unserialize($tsAdmin);
`

Leider ist unserialize($tsAdmin) immer leer. Gibt es dafür eine Lösung?

**Comment by lgund** [comment]
Nachtrag:
Das serializierte Object sieht so aus:

> O:8:"ts3admin":1:{s:17:"ts3adminruntime";a:9:{s:6:"socket";i:0;s:8:"selected";b:1;s:4:"host";s:14:"85.214.197.205";s:9:"queryport";i:10011;s:7:"timeout";i:2;s:5:"debug";a:0:{}s:10:"fileSocket";s:0:"";s:8:"bot_clid";s:1:"2";s:8:"bot_name";s:37:"serveradmin from 85.214.197.205:55832";}}

**Comment by par0noid** [comment]
Ich glaube nicht das serialisieren Sinn macht. Die Klasse verwaltet ja aktiv eine Verbindung, die kannst du nicht einfach ablegen und bei bedarf wieder laden weil Teamspeak 3 dich in der Zeit schon lange aus dem Query geworfen hat.

**Comment by lgund** [comment]
Mein Ziel ist es statt ständig über ajax eine neue verbindung aufzubauen, diese Verbindung einfach mitzuschicken. Sprich das beim Aufruf der Seite eine Verbindung geöffnet wird und per ajax diese mitgegeben wird.

**Comment by par0noid** [comment]
Okay, das könnte natürlich Sinn machen 😄 jetzt ist nur die Frage warum es nicht funktioniert, ich probiere es bei mir auch gerade mal aus. BTW: ich hab oben dein serveradmin Passwort mal zensiert 👍

**Comment by par0noid** [comment]
Also bei mir funktioniert es.

var_dump vom serialisierten:
`string(275) "O:8:"ts3admin":1:{s:17:"ts3adminruntime";a:9:{s:6:"socket";i:0;s:8:"selected";b:1;s:4:"host";s:9:"127.0.0.1";s:9:"queryport";i:10011;s:7:"timeout";i:2;s:5:"debug";a:0:{}s:10:"fileSocket";s:0:"";s:8:"bot_clid";s:1:"2";s:8:"bot_name";s:31:"serveradmin from 127.0.0.1:2562";}}"`

var_dump vom deserialisierten.
`object(ts3admin)#2 (1) { ["runtime":"ts3admin":private]=> array(9) { ["socket"]=> int(0) ["selected"]=> bool(true) ["host"]=> string(9) "127.0.0.1" ["queryport"]=> int(10011) ["timeout"]=> int(2) ["debug"]=> array(0) { } ["fileSocket"]=> string(0) "" ["bot_clid"]=> string(1) "2" ["bot_name"]=> string(31) "serveradmin from 127.0.0.1:2562" } }`

**Comment by lgund** [comment]
Ok und wie hast du es derialsiert? so wie ich oben?

**Comment by par0noid** [comment]
Ja, allerdings verliert das Script die Verbindung beim Serialisieren

**Comment by par0noid** [comment]
`	print_r($tsAdmin->hostinfo());
	
	$s = serialize($tsAdmin);
	
	echo '<hr>';
	
	print_r(unserialize($s)->hostinfo());`

**Ausgabe:**

`Array ( [success] => 1 [errors] => Array ( ) [data] => Array ( [instance_uptime] => 279 [host_timestamp_utc] => 1485949449 [virtualservers_running_total] => 1 [virtualservers_total_maxclients] => 32 [virtualservers_total_clients_online] => 0 [virtualservers_total_channels_online] => 1 [connection_filetransfer_bandwidth_sent] => 0 [connection_filetransfer_bandwidth_received] => 0 [connection_filetransfer_bytes_sent_total] => 0 [connection_filetransfer_bytes_received_total] => 0 [connection_packets_sent_total] => 0 [connection_bytes_sent_total] => 0 [connection_packets_received_total] => 0 [connection_bytes_received_total] => 0 [connection_bandwidth_sent_last_second_total] => 0 [connection_bandwidth_sent_last_minute_total] => 0 [connection_bandwidth_received_last_second_total] => 0 [connection_bandwidth_received_last_minute_total] => 0 ) )


Array ( [success] => [errors] => Array ( [0] => Error: script isn't connected to server ) [data] => )`

**Comment by par0noid** [comment]
Die PHP-Dokumentation sagt: 

> Der zu serialisierende Wert. serialize() kann mit allen Typen umgehen, ausgenommen mit dem resource-Typ. 

Du wirst das Handle also niemals serialisieren können, wie ich eingangs schon vermutet hatte

**Comment by lgund** [comment]
> Error: script isn't connected to server

Hab ich nun leider auch. Das ist ja blöd.... Fällt dir da eine Idee zu meinem Problem ein?

Ich selbst habe nämlich ein flood problem wegen zu vieler Anmeldungen. Wollte es damit eben auf eine aktive beschränken und vor allem sieht das echt *** aus, wenn man im Teamspeakserver immer den queryclienten rein und raus kommen sieht...

**Comment by par0noid** [comment]
Siehe Antwort vor Deiner bezüglich Problemlösung.

Den Queryclient siehst du nur im TS wenn du das angehakt hast, normale Nutzer sehen den nicht. Das Flood-Problem lässt sich mittels Whitelisteintrag beheben

**Comment by lgund** [comment]
> Flood-Problem lässt sich mittels Whitelisteintrag beheben

Leider sind teilweise zuviele Anmeldung gewesen, sodass trotz whitelisting die verbindungen von 10 auf 100 hochgestuft werden mussten. Und das ist eine blöde Lösung.

Aber nagut dann scheint meine Idee nicht umsetzbar zu sein :(

**Comment by par0noid** [comment]
Würde dir da gerne helfen, aber das sind halt Beschränkungen die von Teamspeak gemacht sind, da kann ich leider auch nichts machen 😞 

Du könntest höchstens einen Dienst programmieren der Aktiv eine Verbindung zu Teamspeak verwaltet mit dem du dich wiederum dann so oft verbinden kannst wie du willst. Der Dienst wäre dann allerdings PHP unabhängig, quasi eine Art "Gateway"

**Comment by lgund** [comment]
Das ist richtig, aber sowas finde ich immer sehr instabil, wenn ich ein php script unlimted laufen lasse mit while(1).... Nagut dann muss ich mir ne andere Lösung suchen. Mein Idee war schon mit Javascript, aber dort gibt es ebenfalls nichts einfaches. Node.js ist auch nicht so einfach zu installieren....

**Comment by par0noid** [comment]
Ich halte diese ganze Sache mit Querys immer für ein wenig instabil, ist halt immer blöd wenn man eine Verbindung zu Extern aufbaut aus der man dann Daten zur Darstellung einer Website bezieht. Ansonsten cache die Daten doch wenn es nicht absolut "live" sein muss

**Comment by lgund** [comment]
Nagut... war immerhin eine Idee.... Danke für die schnelle Hilfe!
