### ISSUE TITLE
readChatMessage while(1)?

### ISSUE THREAD

**Issue by lgund** [par0noid/ts3admin.class#25]
Hey,
wenn ich folgendes tue....
`$test		=	$tsAdmin->getElement('data', $tsAdmin->readChatMessage('textserver'));`

dann wird die Seite solange nicht geladen, bis jemand was im Server schreibt. Ich habe im Quelltext nicht den Grund gefunden warum das so ist. Gibt es eine Möglichkeit zu prüfen, ob was geschrieben wurde und wenn ja das zurückzugeben und wenn nicht ein leeres Resultat zurückzugeben?

**Comment by GryTrean** [comment]
while(true)
	{
		$msgData = $tsAdmin->readChatMessage('textprivate', true);
		if($msgData['success'] == 1) // All went fine
		{
			$msgData = $msgData['data'];
			$clientID = $msgData['invokerid'];
			$clientUID = $msgData['invokeruid'];
			$clientName = $msgData['invokername'];
			$msg = $msgData['msg'];
			$targetMode = $msgData['targetmode'];
		}
	}

**Comment by GryTrean** [comment]
I will also add now, that I don't understand what you wrote, but I guess that you want to learn how to use that function. Well, you see what I wrote, and my guess is that you will be able to work further with that.

Regards,
GryTrean

**Comment by lgund** [comment]
Hey GryTrean,

thanks for your answer. I want to use this function to check if someone write something in the server chat. I would check that with ajax every X seconds. The problem is that if I use the function it's like you have written. The site freezing until someone write something.

Is it possible just to check if something was written in the server chat anf return that? Or isn't it possible cause that damn telnet console doesn't support this....

**Comment by GryTrean** [comment]
You could try to make an if statement and if not completed just use "break".
I am not really sure, I am using a completly new 'file/bot/code" for this.

**Comment by par0noid** [comment]
Sorry für die späte Antwort, bin einfach viel zu sehr mit meiner Arbeit beschäftigt 😢 

Die Funktion readChatMessage kann nach meinen Informationen keine Nachrichten aus der Vergangenheit abrufen. Ruft man die Funktion auf, so wird quasi auf dem Server ein "eventHandler" initialisiert der im Falle einer Nachricht eine Rückgabe dieser an das Query gibt. Somit kann die Funktion nicht vorher beendet sein. Ein Überprüfen ob etwas geschrieben wurde ist mit dieser Funktion nicht möglich. Teamspeak bietet keine Funktion dafür. Du könntest höchstens etwas mit Hilfe der Log-Methoden machen

**Comment by lgund** [comment]
Nagut schade.. Also ist meine Idee futsch eine Art teamspeak Chatmessenger zu bauen :D

**Comment by par0noid** [comment]
Du könntest nur eventuell (bin mir da aber auch nicht sicher) was mit der logView Methode machen, sofern da Chatnachrichten bei sind

**Comment by lgund** [comment]
Ok, also man kann nur über die Logeinstellungen die vergangenen Servernachrichten auslesen. Für mein Interface leider keine Anwendungsmöglichkeit, aber dennoch gut zu wissen ;)
