### ISSUE TITLE
php7 not compatible

### ISSUE THREAD

**Issue by VULCHOK** [par0noid/ts3admin.class#26]
`Compile Error: Cannot use TeamSpeak3\Helper\String as String because 'String' is a special class name`

ts3admin not working for php 7 cause "String" class name is occupied in base PHP 7.

Can you make it compatible ?

**Comment by DavidBonnier** [comment]
Are you sure use https://github.com/par0noid/ts3admin.class/blob/master/lib/ts3admin.class.php ?
In ts3admin.class.php just one class defined is ts3admin.
And me I use with zenserv.fr ts3admin and PHP7 but I don't have a problem ...

**Comment by VULCHOK** [comment]
Ho god -_-

You are totally right, i make an issue on the wrong project.
Ts3admin is working fine with php7.

You can burn this issue
