### ISSUE TITLE
clientDbList gibt nicht alle Clienten zurück...

### ISSUE THREAD

**Issue by lgund** [par0noid/ts3admin.class#27]
Hey ich bins nochmal :D,
ich habe mittlerweile von mehreren Nutzern meine Interfaces die Meldung bekommen, dass nicht alle Datenbankbenutzer angezeigt werden. Wo ich es nun selbst getestet habe, stimmt das leider.

Ich verwende folgende funktion:
[http://ts3admin.info/manual/classts3admin.html#a84896e1a06dffa43811751079dcc04ed](http://ts3admin.info/manual/classts3admin.html#a84896e1a06dffa43811751079dcc04ed)

Im Quelltext frage ich diese ab und gebe sie mit einer einfachen foreach schleife aus. Allerdings sind nicht alle vorhanden. Selbst wenn ich auf dem Teamspeak online bin, werde ich in der Liste nicht angezeigt. Gibt es schon andere Meldungen derart?

Hier gab es schon mal solch ein Post, allerdings sehe ich daraus keine Lösung..:
[https://github.com/par0noid/ts3admin.class/issues/24](https://github.com/par0noid/ts3admin.class/issues/24)

**Comment by Falseee** [comment]
Hast du den Query mal manuell ausgeführt um zu gucken ob dort alles korrekt zurück kommt ?
Wenn nicht liegt es nicht an dieser Klasse.

**Comment by lgund** [comment]
Moment werde ich gleich mal nachschauen :).

Die Seite ist in der jetzigen Version schon relativ sicher. Habe beim rework noch 1-2 XSS lücken gefunden, die werden allerdings mit der neuen Version geschlossen. Falls du noch welche findest schreibe mir das bitte :D.

**Comment by lgund** [comment]
So habe es nun mal ausprobiert und es scheint nicht an der ts3admin.class zu liegen. Wie schon im #24  geschrieben wurde, werden nicht alle clienten aufgelistet. Wenn ich allerdings folgendes in die Console eingebe:

`clientdblist start=0 duration=900`

werden mir alle clienten gezeigt. Ich würde jetzt ungern ein irrsinnig große Zahl angeben. Hat jemand anderes eine Idee?

**Comment by Falseee** [comment]
@lgund 
Kenne mich NOCH nicht so gut aus(Bin dabei ein Webinterface fürs Mangen von Teamspeak Servern zu schreiben), gibt es den eine Methode mit der du die Anzahl der Clients aus der db kriegst ?

**Comment by par0noid** [comment]
@lgund Normalerweise ist es nicht nötig ein Limit anzugeben, aber eventuell hat Teamspeak da ne Macke. Wenn man nichts angibt sollte er von selbst -1 = unlimited wählen. Steht auch so in der Doku. Naja, musst du wohl ne große Zahl nehmen damit es geht... find es auch doof 😢 

@Falseee Wenn du den -count Parameter mitlieferst bekommst du die Anzahl, siehe Doku

**Comment by Falseee** [comment]
@par0noid Wenn Teamspeak wirklich dort spinnt und es eine Method gibt womit man die Anzahl der Clients holen kann, dann könnte man ja das Limit auf die Anzahl setzen statt auf -1.

Geht natürlich nur wenn die Anzahl stimmt.

**Comment by par0noid** [comment]
@Falseee Ja ich bin mir gerade nicht sicher ob der count alle Clients zurück gibt, oder nur die Anzahl der ausgelesenen. Das müsste ich ggf. sobald ich Zeit hab prüfen. Ansonsten nimm doch einfach eine hohe Zahl und das Ding läuft 😆
