### ISSUE TITLE
Composer autoload funktioniert nicht

### ISSUE THREAD

**Issue by Falseee** [par0noid/ts3admin.class#28]
Hallo,

kurz und knapp: wenn ich wie gewohnt bei composer nur die autoload.php include kann die Klasse ts3admin nicht gefunden werden.
Evtl. sollte in Klasse mal ein namespace erstellt werden und das autload angepasst werden.

Nebenfrage:
Wieso besteht das Projekt nur aus einer Klasse ?
Das ganze ist doch nicht wirklich (2017) oop, beim holen von den Server (serverList Funktion) bekommt man nur ein Array mit den Werten...
Wieso wird dort z.b. kein Array aus Server Klassen wiedergeben und an denen kann man die Informationen holen ?
Also z.b.

```php

$ts3admin = new ts3admin("ip", 10011);
$ts3admin->login("login", "pw");

$serverList = $ts3admin->serverList();

foreach ($serverList as $index => $server)
{
      echo "Id:" . $server->getId() . PHP_EOL;
      echo "Maximale Clienten:" . $server->getMaxClientCount() . PHP_EOL;
}
```

**Comment by Falseee** [comment]
@par0noid Meinst du es wäre bald möglich das Autoloading einzubauen ?

**Comment by par0noid** [comment]
@Falseee Wenn du die Rückgabe in OOP-Style haben möchtest, dann nutz das teamspeak Framework. Diese Klasse verzichtet mit Absicht auf Namespaces, zusätzliche Klassen und co. um anfängertauglich zu sein. Für alle Fortgeschrittenen stehen andere Frameworks zur Verfügung.

Bei mir funktioniert das Autoloading einwandfrei, eventuell solltest du dein Coding prüfen.

**Comment by Falseee** [comment]
```php
require_once "../vendor/autoload.php";
$ts3admin = new ts3admin("domain.de", 10011);
```
@par0noid 
Was soll daran falsch sein ?
Gibt ja eigentlich nichts was man falsch machen kann...

Von was für einen Framework sprichst du ?
Die ich gefunden habe waren scheiße oder nur zu 40% OOP.

**Comment by par0noid** [comment]
@Falseee eigentlich ist nichts falsch, ich mache es bei mir so wie du:

```php
require __DIR__ . '/vendor/autoload.php';
$tsAdmin = new ts3admin($ts3_ip, $ts3_queryport);
```

und es funktioniert prima, das Problem muss bei dir an einer anderen stelle liegen.

Ich rede von diesem Framework: [https://docs.planetteamspeak.com/ts3/php/framework/](url)

**Comment by Falseee** [comment]
@par0noid 
Hmm habe gerade nochmal es neu runtergeladen mit Composer und es geht nicht ;o
Weder auf dem Server noch lokal... seltsam..

Naja sobald es läuft werde ich dennoch dieses hier nutzen, das Framework was du gepostet hast war das was zu 50% nur oop ist..

Baue mir einfach ein Wrapper für deine Funktionen.

**Comment by par0noid** [comment]
@Falseee komisch dass das bei dir nicht klappt. Ich weiß dass es bei mir und auch anderen funktioniert, wo genau jetzt der Hund begraben liegt kann ich dir leider nicht sagen 🤔
