### ISSUE TITLE
Join with a specific Identity

### ISSUE THREAD

**Issue by FFY00** [par0noid/ts3admin.class#30]
How to use a specific Identity to join the server?

**Comment by lgund** [comment]
You can just create an Identity. I am not sure if you can choose one you like, but I think it´s just random (All other would be a security problem).

**Comment by FFY00** [comment]
I've been experimenting with this and looks like the Server Query uses the Identity of the user that created it but my question is how do I specify a Identity when using a unauthenticated server query?

**Comment by par0noid** [comment]
You can define your identity with your login credentials. There's no other option given by teamspeak.
