### ISSUE TITLE
Calling values

### ISSUE THREAD

**Issue by fulltimehobo** [par0noid/ts3admin.class#34]
how would I call the values for online clients and max clients?

**Comment by lgund** [comment]
Code example?

**Comment by fulltimehobo** [comment]
I'm looking for a code example just so I can understand it.

**Comment by lgund** [comment]
It's in German, but the source should be easy to understand :)

https://www.teamspeak-connection.de/Thread/155-Webprogrammierung-fuer-Teamspeak-mit-der-ts3admin-class/
