### ISSUE TITLE
Error during selecting server

### ISSUE THREAD

**Issue by czerwony04** [par0noid/ts3admin.class#35]
Hi,
I have problem with connecting to few servers, and I don't know what's going on :/.

`Warning:  Invalid argument supplied for foreach() in /var/www/***.pl/public_html/***/ts3admin.class.php on line 3208`

Code:
`	$tsAdmin = new ts3admin($config["ts3"]["ip"], $config["ts3"]["queryport"]);
	$tsAdmin->connect();
	$tsAdmin->login($config["ts3"]["user"], $config["ts3"]["pass"]);
	$tsAdmin->selectServer($config["ts3"]["port"]);`

Server:
`51.254.11.77:9987`
and
`185.101.94.165:9987`

Any suggestions?

Best regards,
Mariusz W.
czerwony03

**Comment by lgund** [comment]
Where is your error?

> Warning: Invalid argument supplied for foreach() in /var/www/***.pl/public_html/***/ts3admin.class.php on line 3208

This is the Warning. Maybe is the foreach variable empty?

**Comment by czerwony04** [comment]
After that warning every other method (for example client/channel list) fail.

There is problem with selecting server by port, and i don't know what's causing the problem.

**Comment by lgund** [comment]
Read the Documentation:
http://ts3admin.info/manual/classts3admin.html#a59c926b08f706f7b5baec89bf91c7170

Change that
`$tsAdmin->selectServer($config["ts3"]["port"]);`

to that
`$tsAdmin->selectServer($config["ts3"]["port"], 'port');`

But that shouldn´t fix the problem, cause the selecting server by port is default in the method.

Just write after the selecting this and show on the webpage what the error is:
`print_r($tsAdmin);`

**Comment by czerwony04** [comment]
[debug] => Array
                (
                    [0] => Error in clientList() on line 1864: ErrorID: 2568 | Message: insufficient client permissions failed_permid=27
                )

**Comment by lgund** [comment]
The queryuser you use as login into the teamspeak telnet has not enough permissions. You need to set the permission.

The selection was successful:)
