### ISSUE TITLE
Problem with readChatMessage

### ISSUE THREAD

**Issue by Nowson04** [par0noid/ts3admin.class#36]
Hello,

I've got a problem with a readChatMessage function. 
Here is my code:
" $ts3->readChatMessage("textchannel",false,'1') ".

This code should read the message from channel with id 1 but it's not working properly. It reads message only from default channel. How to fix it?

I'd really appreciate your help.

Best regards,
Kuba Nowacki

**Comment by lgund** [comment]
I think it's cause you send a string as Channelid, but a int is required. You see [here](http://ts3admin.info/manual/classts3admin.html#a044041553b2514cbe34367cd71bba4d1), how it would work you need to change:

> $ts3->readChatMessage("textchannel",false,'1');

this to ...

> $ts3->readChatMessage("textchannel",false,1);

that.

**Comment by Nowson04** [comment]
It's not working, I've already tried it.
My default channel has ID 6, bot only works there.

**Comment by Nowson04** [comment]
Problem solved. When server starts script changes default channel to id=1. Secondly another bot with readChatMessage login to default channel with id 1. After all default channel changes id to 6 ;)
It's not perfect solution but it works :)
