### ISSUE TITLE
Teaspeak Support

### ISSUE THREAD

**Issue by lgund** [par0noid/ts3admin.class#39]
Hey,
I´am not sure, but for some reason [Teaspeak ](https://teaspeak.de/)will not work with your Script. If I check manuely the Telnet connection the telnet looks the same like Teamspeak.

> TeaSpeak
Welcome on the TeaSpeak ServerQuery interface.
login serveradmin *****
error id=0 msg=ok
use 1
notifyclientupdated clid=0
error id=0 msg=ok
clientlist
clid=1 cid=4 client_database_id=2 client_nickname=test client_type=0|clid=2 cid=0 client_database_id=1 client_nickname=serveradmin client_type=1
error id=0 msg=ok

Message in the Teaspeak console:
> [03:07:43] [INFO] [Query] Got new client from 62.75.187.128:33474
[03:07:43] [ERROR] Query invalid read. Code: 0 errno: 0 msg: Success

Did you have an Idea what´s wrong?

**Comment by FFY00** [comment]
You need to contact the developers, not the author of this script.

**Comment by lgund** [comment]
If that´s so...
