### ISSUE TITLE
clientAvatar($uid) infinite loop

### ISSUE THREAD

**Issue by Nik99** [par0noid/ts3admin.class#4]
Hi, i'm trying to setup an API for getting clientAvatar but, when i'm running this file, it does an infinite loop.

That's my code:

$node = new ts3admin($data->ip, $data->sq_port);
    if($node->getElement('success', $node->connect())) {
      if ($node->getElement('success', $node->login($data->sq_username, $data->sq_password))) {
        if($node->getElement('success', $node->selectServer($virtualserver_id, 'serverId', true))) {
          $response = $node->clientAvatar($client);
        } else {
          $response = false;
        }
      } else {
        $response = false;
      }
    } else {
      $response = false;
    }

Is this a bug or am i missing something? Thanks

**Comment by par0noid** [comment]
What is in $client?

**Comment by Nik99** [comment]
I tried every value from current client id, database client id, client unique identifier, system always crashes.

**Comment by par0noid** [comment]
I used your code, set $client to the unique identifier and it works very well. Mabye you're doing something wrong with filetransferports/firewall?

**Comment by par0noid** [comment]
btw. which ts3 server version do you use

**Comment by Nik99** [comment]
My own test server is using 3.0.13.3 [Build: 1471538803] on Windows.
The website is on to a linux hosting.

So, to make the function work i need to set $client with the unique identifier?
What do you mean for something wrong with filetransports / firewall?

**Comment by Nik99** [comment]
Btw, can you please give me your test code? So i can try it

**Comment by par0noid** [comment]
I used your code
You should try to use the filetransfer functions, if these functions wont work either - then there has to be a filetransfer problem

**Comment by Nik99** [comment]
It worked, thanks.
It was a windows firewall problem that was blocking FileTransfer servers.

**Comment by Nik99** [comment]
Here i am again...
I founded that if a user doesn't have a avatar, the system does an infinite loop.

Wouldn't be better if it throws an error?

**Comment by Viper61** [comment]
Looks like there isn't an infinite loop. When trying to get an avatar that doesn't exist, TeamSpeak seems to simply not answer.

Here the answer i got when checking in telnet :

- User with avatar :

>clientftfid=61 serverftfid=2 ftkey=gBWgqxbptF791qx0ZQXc5J2xHQmva6eX port=30033 size=23779 proto=0
>error id=0 msg=ok

- User whithout avatar :

> [blank]

Note : Can't do anything pass this step, have to kill/restart the process

**Comment by Nik99** [comment]
Exactly, the only way to stop it is to restart the process.

So is this actually a teamspeak fault ?

**Comment by Viper61** [comment]
Found a way to get around this using ftgetfileinfo. I will make a PR in few minutes ;)

**Comment by Nik99** [comment]
Good Job Viper.

Let's wait a response from par0noid.

**Comment by par0noid** [comment]
Thanks a lot for finding out whats the reason for the problem and your pull request.

I merged your request and released a new version for it!
