### ISSUE TITLE
Read Chat Message function not working

### ISSUE THREAD

**Issue by Cyber52** [par0noid/ts3admin.class#43]
Hi,
I'm using ts3admin lib for a long time but I've got a little problem with readChatMessage function.
When I put it to my PHP file, the script drops 504 Gateway Time-out error. I can't get what I'm
doing wrong. I tried to frind a solution with no effect. This is code I'm using:

```
<?php
define('ROOT_DIR', '/var/www/admin/public_html/');

ini_set('max_execution_time', 0);
ini_set('error_log', ROOT_DIR.'cron/error.log');
ini_set('log_errors', 1);

require_once(ROOT_DIR.'classes/TS3Admin.class.php');

$ts3_server['ip'] = 'localhost';
$ts3_server['port'] = 9988;
$ts3_server['queryport'] = 10222;
$ts3_server['user'] = 'serveradmin';
$ts3_server['pass'] = '---';

$ts = new ts3admin($ts3_server['ip'], $ts3_server['queryport']);

$connection = false;
for($i=0; $i<=3; $i++) {
	if($ts->getElement('success', $ts->connect())) { $connection = true; break; }
	sleep(10);
}

if($connection!==true) {
	error_log('Cant\'t reach the server.');
	exit();
}

unset($connection);

$ts->login($ts3_server['user'], $ts3_server['pass']);
$ts->selectServer($ts3_server['port']);

echo $ts->readChatMessage('textprivate');

if(count($ts->getDebugLog()) > 0) {
	foreach($ts->getDebugLog() as $logEntry) {
		echo '<script>alert("'.$logEntry.'");</script>';
	}
}
```

I tried to use this function with a lot of parameters with the same effect, only If i typed not existing "type" name It shows error array.

I tried to do it on newly cretated TS so I dont think Its permissions problem.

I really wan to use this lib so I will be very greatful for help.

Regards

**Comment by par0noid** [comment]
Hey,

can't replicate this error. Note that you can just read private messages to the serverquery, not every private message. Through my tests I have found a mistake that I'll correct in the next version (when you want to read channel messages from the default channel).

Regards
