### ISSUE TITLE
Warning: Invalid argument supplied for foreach() in ts3admin.class.php on line 3208

### ISSUE THREAD

**Issue by Deeonix** [par0noid/ts3admin.class#45]
private function loadQueryData()
{
	$whoAmI = $this->getElement('data', $this->whoAmI());
	$this->runtime['bot_name'] = $whoAmI['client_nickname'];
		
	$clients = $this->clientList();
	foreach($clients['data'] as $client)	// Here is the line
	{
		if(strstr($this->runtime['bot_name'], $client['client_nickname']))
		{
			$this->runtime['bot_clid'] = $client['clid'];
			break;
		}
	}
}

**Comment by par0noid** [comment]
I don't have these problems, can't really get how you're using the class. Did you inherit the class? Because you're using $this->

**Comment by Deeonix** [comment]
I require the class.

The function from above is your Code.

**Comment by lgund** [comment]
You could also use php empty

**Comment by par0noid** [comment]
Did you check "success" of the result-array? Did you take a look at [getDebugLog()](http://ts3admin.info/manual/classts3admin.html#a1f5f0bfffa7e348c26c7087a9af2f0d6) ?
