### ISSUE TITLE
'channel_needed_subscribe_power' ist immer auf 0

### ISSUE THREAD

**Issue by dhavenith** [par0noid/ts3admin.class#46]
Moin,

bei channelList() ist der Wert von "channel_needed_subscribe_power" immer auf 0. Ich habe dies nun auf mehreren Teamspeak-Servern gesteset. Ist Dir da ein Fehler bekannt?

Gruß Daniel

**Comment by par0noid** [comment]
Tatsächlich ist es so, auch wenn man die channel_needed_subscribe_power geändert hat.
Der Fehler kommt allerdings auch direkt vom Teamspeak selbst, der Server liefert die Information schon so.

cid=1 pid=0 channel_order=0 channel_name=Default\sChannel total_clients=2 channel_needed_subscribe_power=0
error id=0 msg=ok

Eventuell müsste man einen bugthread im teamspeak Forum öffnen
