### ISSUE TITLE
Using serverInfo() instead of serverList()

### ISSUE THREAD

**Issue by Zerefdev** [par0noid/ts3admin.class#48]
Hello,
I was playing around with the framework and I had issues with **serverInfo()**, I'd like some help

For example:

```
...
if($tsAdmin->getElement('success', $tsAdmin->connect())) {
	$tsAdmin->login($ts3_user, $ts3_pass);

	$servers = $tsAdmin->serverList();

	foreach($servers['data'] as $server) {
		echo $server['virtualserver_name'];
	}
	$tsAdmin->logout();
}
```
**Output as expected** 
Perfect! 
But using serverInfo() + selectServer() :

```
...
if($tsAdmin->getElement('success', $tsAdmin->connect())) {
	$tsAdmin->login($ts3_user, $ts3_pass);
	$tsAdmin->selectServer($ts3_port);

	$servers = $tsAdmin->serverInfo();

	foreach($servers['data'] as $server) {
		echo $server['virtualserver_name'];
	}
	$tsAdmin->logout();
}
```
**Output**
`Warning: Illegal string offset 'virtualserver_name' in /xxx/www/serverlist.php on line XX`

Am I missing something?

**Comment by Zerefdev** [comment]
It seems like I can't get info from that array but I can list the whole array
```
	foreach($servers['data'] as $server) {
		echo $server . '<br>';
	}
	$tsAdmin->logout();
}
```
or
```
	foreach($servers['data'] as $server => $servervalue) {
		echo $server . ' - ' . $servervalue . '<br>';
	}
	$tsAdmin->logout();
}
```
**Output** as expected:
```
virtualserver_unique_identifier - XYBeHPfTMqweyXXXXX1fQmqsadcWE=
virtualserver_name - Teamspeak 3 Server Name
virtualserver_welcomemessage - 
virtualserver_platform - Linux
...etc
```

**Comment by par0noid** [comment]
Serverinfo returns an array, Serverlist returns a multidimensional array. You can't iterate trough a serverinfo array because it's the info of just one server.

`$servers = $tsAdmin->serverInfo();

echo $servers['data']['virtualserver_name'];`

Should work fine

**Comment by Zerefdev** [comment]
I understand now!
Thank you
