### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by lgund** [par0noid/ts3admin.class#5]
Verbindung über einem Ipv6 Teamspeak server schlägt fehl. Werden diese nicht unterstützt? Falls ja gibt es demnächst eine Unterstützung?

**Comment by orloffIT** [comment]
Fehler bereits gefunden.
Bei der Funktion "fsockopen" ist darauf zu achten, dass IPv6-Adressen im Format "[<ipv6addr>]" angegeben werden. Ansonsten wird der String als DNS-Name interpretiert, und somit die falsche Stelle angesprochen.

**Comment by par0noid** [comment]
@orloffIT für mich hieße es das ich ja dann jetzt gar nichts für IPv6 Untersützung zu implementieren brauche, oder sehe ich das falsch?

**Comment by lgund** [comment]
Nein ich muss bloß erkennen, falls es sich eine IPv6 Adresse handelt die [] hinzufügen 👍
