### ISSUE TITLE
Server version 3.4.0 nickname changes

### ISSUE THREAD

**Issue by Pantoflarz** [par0noid/ts3admin.class#57]
As per https://forum.teamspeak.com/threads/137292-Release-TeamSpeak-3-Server-3-4-0

Could we make use of 

"1. Now you can give your query client a nickname before you select a server and the users on server will no longer see the default user name with current IP. The parameter is optional and without it you get the default nickname when you select a server."

in ts3admin class?

Thanks

**Comment by Pantoflarz** [comment]
fixed in pull request - 

https://github.com/par0noid/ts3admin.class/pull/61

**Comment by par0noid** [comment]
merged 👍
