### ISSUE TITLE
ts3 status - question

### ISSUE THREAD

**Issue by RedstoneFuture** [par0noid/ts3admin.class#58]
Hello. I have not the big PHP skill and would like know, why I can't get the server status with my PHP code:

```
if($tsAdmin->getElement('success', $tsAdmin->connect())) {
	#login as serveradmin
	$tsAdmin->login($ts3_user, $ts3_pass);
	
	#select teamspeakserver
	$tsAdmin->selectServer($ts3_port);
	
	#get clientlist
	$clients = $tsAdmin->clientList();
	
	#get status (!!!!)
	$status = $tsAdmin->serverInfo();
	
	#print client count
	echo count($clients['data']) . ' clients on selected server<br><br>';
	
	#print server status (!!!!)
	echo $status['virtualserver_status'];
	
	#print clients to browser
	foreach($clients['data'] as $client) {
		echo $client['client_nickname'] . '<br>';	
	}
}else{
	echo 'Connection could not be established.';
}
```

The server-status request and the echo are not correctly. I don't why. I inspired my of the other code-lines.

`[virtualserver_status]` under the serverInfo array get the server satus.

**Comment by SantiagoAcevedo** [comment]
`[virtualserver_status]` only in `serverList()` Ex. `$servers = $tsAdmin->serverList();`

> Array
{
 [virtualserver_id] => 1 //displayed on -short
 [virtualserver_port] => 9987 //displayed on -short
 [virtualserver_status] => online //displayed on -short
 [virtualserver_clientsonline] => 2
 [virtualserver_queryclientsonline] => 1
 [virtualserver_maxclients] => 32
 [virtualserver_uptime] => 3045
 [virtualserver_name] => TeamSpeak ]I[ Server
 [virtualserver_autostart] => 1
 [virtualserver_machine_id] =>
 [-uid] => [virtualserver_unique_identifier] => bYrybKl/APfKq7xzpIJ1Xb6C06U= 
}
**In `$tsAdmin->serverInfo();` you can get:**

> Array
{
 [virtualserver_unique_identifier] => 1GvKR12fg/mY75flwN/u7pn7KIs=
 [virtualserver_name] => TeamSpeak ]I[ Server
 [virtualserver_welcomemessage] => Welcome to TeamSpeak, check [URL]www.teamspeak.com[/URL] for latest information
 [virtualserver_platform] => Windows
 [virtualserver_version] => 3.0.12.4 [Build: 1461597405]
 [virtualserver_maxclients] => 32
 [virtualserver_password] => 
 [virtualserver_clientsonline] => 2
 [virtualserver_channelsonline] => 1
More in - [http://ts3admin.info/manual/classts3admin.html#a403eff6de16fadd41ddc4155d6dbd09c](http://ts3admin.info/manual/classts3admin.html#a403eff6de16fadd41ddc4155d6dbd09c)

 }

**Comment by SantiagoAcevedo** [comment]
Test like this.
**Set the virtual server ID in `$serverid = 1;`**
```
if($tsAdmin->getElement('success', $tsAdmin->connect())) {
	#login as serveradmin
	$tsAdmin->login($ts3_user, $ts3_pass);
	
	#select teamspeakserver
	$tsAdmin->selectServer($ts3_port);
	
	#get clientlist
	$clients = $tsAdmin->clientList();
	
	#get status (!!!!)
	$status = $tsAdmin->serverInfo();
	
	#get serverlist
	$servers = $tsAdmin->serverList();
	
	#print client count
	echo count($clients['data']) . ' clients on selected server<br><br>';
	
	#print server status (!!!!)
	echo $status['virtualserver_status'];
	
	#print clients to browser
	foreach($clients['data'] as $client) {
		echo $client['client_nickname'] . '<br>';	
	}
	#print servers to browser
	foreach($servers['data'] as $server) {
		//SET SERVER ID
		$serverid = 1;
		if($server['virtualserver_id'] != $serverid){
            continue;
        }
		echo $server['virtualserver_status'] . '<br>';	
	}
}else{
	echo 'Connection could not be established.';
}
```

**Comment by RedstoneFuture** [comment]
@SantiagoAcevedo 
`[virtualserver_status] => online` is like the documentation in serverinfo() too. Or I missunderstand the documentation.
But with your code it works, thanks.
