### ISSUE TITLE
Events in TS3Admin.Class

### ISSUE THREAD

**Issue by marv-th** [par0noid/ts3admin.class#64]
Hallo.

Ich würde gerne wissen, ob es möglich ist, sich für Events zu registrieren. Bspw. für das Event notifycliententerview. Ähnlich wie es beim ts3phpframework möglich ist.

Ich freue mich über jede hilfreiche Antwort.

LG Marvin

**Comment by lgund** [comment]
Events können auch bei dieser Klasse registriert werden. Falls in der Dokumentation dazu keine öffentliche Funktion existiert, kannst du diese einfach manuell über [diese](http://ts3admin.info/manual/classts3admin.html#a574273700319037ac7338ba7023112b3) einschreiben. Allerdings würde ich nicht empfehlen so etwas über PHP zu machen. Das hat den einfachen Grund, da du das Script dauerhaft laufen lassen müsstest um auf eventuelle Events zu reagieren. Dies wäre nicht gerade ressourcenarm.
