### ISSUE TITLE
clientDbList() returning errors

### ISSUE THREAD

**Issue by Nik99** [par0noid/ts3admin.class#7]
Hi, i was trying to use the function clientDbList(), but the default parameter duration (-1) return this error: 

ErrorID: 1540 | Message: convert error

This is my code:

$node = new ts3admin($data->ip, $data->sq_port);
    // Se l'oggetto è stato creato -> connetti al server
    if($node->getElement('success', $node->connect())) {
      // esegui il login come server query admin
      if ($node->getElement('success', $node->login($data->sq_username, $data->sq_password))) {
        if($node->getElement('success', $node->selectServer($virtualserver_id, 'serverId', true))) {
          $node->setName("xx");
          $response = $node->clientDbList();
        } else {
          $response = false;
        }
      } else {
        $response = false;
      }
    } else {
      $response = false;
    }

If i put in it params like $node->clientDbList(0, 5, false) the function works.

**Comment by par0noid** [comment]
I will take a look at it today

**Comment by Nik99** [comment]
Found anything ?

**Comment by par0noid** [comment]
Oh sorry, i'm Very busy atm,hope i can take a look at it tomorrow

**Comment by Nik99** [comment]
Don't worry, it's fine.

**Comment by par0noid** [comment]
Fixed the problem, -1 in duration seems to be unsupported since some versions. You can just use -1 to define that there's no limit.

https://github.com/par0noid/ts3admin.class/commit/56cff9e1210e77db211ec1cea392e6221ddb97a3
